# 1.向前计算
## 例子1
requires_grad=True设置为True，则改tensor进行的所有操作都会被计算出来，会追踪所有操作，默认在为flase
![](myimg/gs.png)

In [27]:
import torch
#设置为True，进行的所有操作都会被计算出来，会追踪所有操作
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


AddBackward0表示进行了add操作

In [28]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
z =y*y*3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [30]:
#求均值
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


x的每次计算都会修改frand_fn属性，用作记录做过的操作

## 例子2

In [ ]:
a = torch.rand(2,2)
a =(a*3)/(a-1)
#默认为flase
print(a.requires_grad)

In [ ]:
b=(a*a).sum()
print(b.grad_fn)
#不会进行记录

In [ ]:
#其中的操作不会被追踪
with torch.no_grad():
    c = (a*a).sum()
print(c.requires_grad)

# 2.梯度计算
out.backward()就可以进行反向传播，计算梯度，然后会保存到x.grad中获取导数值


In [43]:
out.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [46]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

注意
+ tensor.data
    + 若requires_grad=False,tensor.data和tensor等价
    + require_grad =Ture时候，tensor.data仅仅是tensor的数据
+ tensor.numpy
    + requires_grad=True不能够直接转换，需要用tensor.detach.numpy

In [47]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [48]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

# 3.线性回归的实现
+ 准备数据
+ 计算预测值
+ 计算损失，把参数的梯度设为0，进行反向传播
+ 更新参数