# 张量Tensor
张量是一个统称
1. 0阶张量：标量：常数：scaler:0-D Tensor 
2. 1阶张量：向量：vector:1-D Tensor
3. 2阶张量：矩阵:matrix:2-D Tensor
...
# Pytorch创建张量

In [11]:
import numpy as np
import torch

大写Tensor为小数，小写为整数

In [21]:
t1=torch.Tensor([1,2,3])
t1

tensor([1., 2., 3.])

np.arange([start, ]stop, [step, ]dtype=None)
从哪个数开始，到那个数结束，步长是多长

In [23]:
array1 = np.arange(12).reshape(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

torch和num转换

In [24]:
torch.Tensor(array1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

## torch的api创建tensor
+ torch.empty(3,4):3行4列的空tensor
+ torch.ones([3,4]):3行4列的全为1tensor
+ torch.zeros([3,4]):3行4列的全为0tensor
+ torch.rand([3,4]):3行4列的随机数tensor

In [26]:
torch.empty(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### rand部分

In [29]:
torch.rand(3,4)

tensor([[0.4712, 0.4505, 0.1136, 0.9068],
        [0.2866, 0.3578, 0.6065, 0.9174],
        [0.5756, 0.4597, 0.7982, 0.0219]])

区间：[low,high)

In [30]:
torch.randint(low=0,high=10,size=[3,4])

tensor([[9, 6, 6, 5],
        [7, 5, 1, 9],
        [5, 0, 7, 3]])