# 一.张量Tensor
张量是一个统称
1. 0阶张量：标量：常数：scaler:0-D Tensor 
2. 1阶张量：向量：vector:1-D Tensor
3. 2阶张量：矩阵:matrix:2-D Tensor
...
# 二.Pytorch创建张量

In [11]:
import numpy as np
import torch

大写Tensor为小数，小写为整数

In [21]:
t1=torch.Tensor([1,2,3])
t1

tensor([1., 2., 3.])

np.arange([start, ]stop, [step, ]dtype=None)
从哪个数开始，到那个数结束，步长是多长

In [23]:
array1 = np.arange(12).reshape(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

torch和num转换

In [24]:
torch.Tensor(array1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

## 1.torch的api创建tensor
+ torch.empty(3,4):3行4列的空tensor
+ torch.ones([3,4]):3行4列的全为1tensor
+ torch.zeros([3,4]):3行4列的全为0tensor
+ torch.rand([3,4]):3行4列的随机数tensor

In [26]:
torch.empty(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 2.rand部分

In [29]:
torch.rand(3,4)

tensor([[0.4712, 0.4505, 0.1136, 0.9068],
        [0.2866, 0.3578, 0.6065, 0.9174],
        [0.5756, 0.4597, 0.7982, 0.0219]])

区间：[low,high)

In [31]:
torch.randint(low=0,high=10,size=[3,4])

tensor([[5, 8, 7, 0],
        [8, 6, 5, 2],
        [6, 3, 2, 1]])

满足正态分布的随机数

In [33]:
torch.randn([3,4])

tensor([[-0.1704, -0.1806,  0.1441, -0.1719],
        [-1.3407,  1.0998, -0.2443, -0.5404],
        [ 0.2771,  1.1747, -0.0433, -0.9056]])

# 三. Pytorch的tensor的常用方法

In [36]:
t1 =torch.Tensor([[[1]]])
t1

tensor([[[1.]]])

## 1.获取tensor数据，只有中间的值的时候

In [39]:
t1.item()

1.0

如果里面有两个数呢:将会报错，只有标量才能获得

In [41]:
t2 = torch.Tensor([[[1,2]]])
t2.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

## 2.转为numpy类型

In [45]:
t2.numpy()

array([[[1., 2.]]], dtype=float32)

## 3.获取形状
size可以查看具体的维度

In [53]:
t2.size(2)
t2.size(-1)

2

In [58]:
t2.size()

torch.Size([1, 1, 2])

## 4.形状改变
浅拷贝，仅仅改变形状

In [59]:
t2.view([1,2])

tensor([[1., 2.]])

In [65]:
t2.view(-1)

tensor([1., 2.])

In [66]:
t2.view(2,-1)

tensor([[1.],
        [2.]])

## 5.获取维数

In [68]:
t2.dim()

3

## 6.获取最大值最小值

In [73]:
t2.max()

tensor(2.)

In [75]:
t2.min()
t2.std()

tensor(1.)

## 7.转置

In [82]:
t3 =torch.Tensor(np.arange(24).reshape(2,3,4))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [84]:
t3.size()

torch.Size([2, 3, 4])

将0，1维度交换

In [86]:
t3.transpose(0,1)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

轴交换

In [88]:
t3.permute(1,2,0)

tensor([[[ 0., 12.],
         [ 1., 13.],
         [ 2., 14.],
         [ 3., 15.]],

        [[ 4., 16.],
         [ 5., 17.],
         [ 6., 18.],
         [ 7., 19.]],

        [[ 8., 20.],
         [ 9., 21.],
         [10., 22.],
         [11., 23.]]])

## 8.取值

In [90]:
t4=t3.permute(1,2,0)
t4

tensor([[[ 0., 12.],
         [ 1., 13.],
         [ 2., 14.],
         [ 3., 15.]],

        [[ 4., 16.],
         [ 5., 17.],
         [ 6., 18.],
         [ 7., 19.]],

        [[ 8., 20.],
         [ 9., 21.],
         [10., 22.],
         [11., 23.]]])

In [92]:
t4[0,0,0]

tensor(0.)

In [100]:
t4[0]

tensor([[10., 12.],
        [ 1., 13.],
        [ 2., 14.],
        [ 3., 15.]])

In [99]:
t4[0][0][0]=10

In [101]:
t4

tensor([[[10., 12.],
         [ 1., 13.],
         [ 2., 14.],
         [ 3., 15.]],

        [[ 4., 16.],
         [ 5., 17.],
         [ 6., 18.],
         [ 7., 19.]],

        [[ 8., 20.],
         [ 9., 21.],
         [10., 22.],
         [11., 23.]]])

## 9.tensor切片

In [103]:
t4[:,0]

tensor([[10., 12.],
        [ 4., 16.],
        [ 8., 20.]])

# 四.tenor的数据类型
![](myimg/img.png)

In [106]:
t4.dtype

torch.float32

In [110]:
t5 = torch.tensor([1],dtype=torch.double)
t5

tensor([1.], dtype=torch.float64)

In [113]:
t6=torch.ones((4,3),dtype=torch.double)

In [116]:
t6.dtype

torch.float64

In [136]:
t6.int()

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [138]:
t6.dtype

torch.float64

## 5.tensor的其他操作
+ tensor和tensor相加
    add和直接相加一样效果，不会有影响

In [4]:
import torch
x =torch.ones([5,3],dtype=torch.float)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
y = torch.rand(5,3)
y

tensor([[0.6348, 0.1243, 0.2417],
        [0.8091, 0.2588, 0.8975],
        [0.4358, 0.0061, 0.1221],
        [0.8434, 0.6096, 0.7707],
        [0.3223, 0.4922, 0.7856]])

In [8]:
x+y

tensor([[1.6348, 1.1243, 1.2417],
        [1.8091, 1.2588, 1.8975],
        [1.4358, 1.0061, 1.1221],
        [1.8434, 1.6096, 1.7707],
        [1.3223, 1.4922, 1.7856]])

In [13]:
torch.add(x,y)

tensor([[2.9045, 1.3728, 1.7250],
        [3.4273, 1.7765, 3.6924],
        [2.3073, 1.0182, 1.3663],
        [3.5303, 2.8287, 3.3122],
        [1.9670, 2.4765, 3.3569]])

add_方法：会把x的值改变

In [14]:
x.add_(y)
x 

tensor([[2.9045, 1.3728, 1.7250],
        [3.4273, 1.7765, 3.6924],
        [2.3073, 1.0182, 1.3663],
        [3.5303, 2.8287, 3.3122],
        [1.9670, 2.4765, 3.3569]])

tensor和数字运算

In [18]:
x=torch.ones([5,4],dtype=torch.int)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [22]:
x+10

tensor([[11, 11, 11, 11],
        [11, 11, 11, 11],
        [11, 11, 11, 11],
        [11, 11, 11, 11],
        [11, 11, 11, 11]], dtype=torch.int32)

CUDA的tensor
在GPU上进行训练，需要把代码操作和转换，把代码提供进行转换

In [24]:
#判断我们电脑是否可以支持gpu执行代码不
torch.cuda.is_available()

True

In [30]:
if torch.cuda.is_available():
    #device：表示在cuda执行代码，输入cpu则使用cpu,也可以输入cuda:0代表使用不同gpu
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    #to方法是转到cpu上了
    print(z.to("cpu",torch.double))

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]], device='cuda:0', dtype=torch.int32)
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)
