# 自动求导

In [1]:
import torch

训练过程中就可以指定x求导
方法1：直接手动定义

In [3]:
x = torch.randn(3,4,requires_grad=True)
x

tensor([[ 0.5079, -2.2771,  0.5609,  1.4770],
        [-2.0243,  1.8269,  0.1751,  0.8320],
        [-0.8801,  0.3554,  1.2082,  0.4928]], requires_grad=True)

方法2，后续添加

In [5]:
x = torch.randn(3,4)
x.requires_grad=True
x

tensor([[-0.9924, -0.7102,  1.5046,  0.3743],
        [-1.9801,  0.5823, -1.1125, -0.1576],
        [ 0.4780,  1.6829, -0.1675,  1.2813]], requires_grad=True)

In [10]:
b = torch.rand(3,4,requires_grad=True)
b

tensor([[0.9452, 0.4658, 0.2649, 0.7263],
        [0.2424, 0.0635, 0.5102, 0.0802],
        [0.3146, 0.1266, 0.2440, 0.2987]], requires_grad=True)

In [11]:
t =x+b
y=t.sum()
y

tensor(5.0658, grad_fn=<SumBackward0>)

损失函数自动求导

In [13]:
y.backward()

In [14]:
b.grad

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])