# torch的基本操作

In [1]:
import torch
torch.__version__

'2.1.1+cu121'

导入包，检查版本

In [4]:
x = torch.empty(5,3)
x

tensor([[-3.1915e+37,  1.4966e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

创建5行3列的矩阵

In [5]:
x =torch.rand(5,3)
x

tensor([[0.1293, 0.2372, 0.3355],
        [0.2913, 0.0695, 0.6159],
        [0.9289, 0.4832, 0.1424],
        [0.9718, 0.1832, 0.7711],
        [0.6145, 0.7055, 0.7212]])

获取个随机值

pytorch:所有的计算都需要转为tensor格式
tensor:张量：最基本的计算单元，框架的底层，相当于一个矩阵

In [13]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

指定矩阵的数据类型为long

In [14]:
x.size()

torch.Size([5, 3])

In [16]:
x = torch.rand(5,3)
x

tensor([[0.3429, 0.6429, 0.0888],
        [0.6008, 0.6030, 0.5776],
        [0.3473, 0.4205, 0.1660],
        [0.5562, 0.4151, 0.1550],
        [0.8329, 0.8328, 0.4138]])

In [17]:
y = torch.rand(5,3)
y

tensor([[0.7038, 0.5652, 0.3837],
        [0.0552, 0.3497, 0.1201],
        [0.6364, 0.4875, 0.5063],
        [0.0938, 0.3913, 0.5100],
        [0.9066, 0.3166, 0.4532]])

In [18]:
torch.add(x,y)

tensor([[1.0467, 1.2082, 0.4725],
        [0.6561, 0.9526, 0.6977],
        [0.9838, 0.9079, 0.6723],
        [0.6501, 0.8064, 0.6650],
        [1.7395, 1.1494, 0.8670]])

# 索引
展示x的全部行，第一列

In [20]:
x[:,0]

tensor([0.3429, 0.6008, 0.3473, 0.5562, 0.8329])

# view操作
+ torch.rand 生成在区间 [0, 1) 内均匀分布的随机数
+ torch.randn 生成从标准正态分布（均值为0，标准差为1）中采样的随机数。
-----------------------------------------------------
+ x.view(16)把4*4拉长成16
+ x.view(-1,8):-1代表自动计算

In [ ]:
x = torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size)

# 与Numpy协同操作
## torch转numpy
ones：代表每个元素都是1

In [22]:
a=torch.ones(5)
b =a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [25]:
import numpy as np
a = np.ones(5)
b= torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)